name: example
description: A example of essential_components library for AngularDart developers. This example is gallery of components
version: 1.0.7
homepage: https://github.com/insinfo/essential_components
authors: 
  - Isaque Neves <insinfo2008@gmail.com> 
  - Thiago Cunha <thiagosantoscunha@outlook.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha+1
  angular_components: ^0.14.0-alpha+1
  angular_router: ^2.0.0-alpha+21
  http: ^0.12.0+4
  stream_transform: ^1.1.0  
  js: ^0.6.1+1
  money: ^0.2.1
  decimal: ^0.3.5
  c3: ^0.1.0
  dio: ^3.0.8
  highlight: ^0.5.0
  sass_builder: ^2.1.2

  # essential_components: 0.1.45
  essential_components:
    path: ../

dev_dependencies:  
  angular_test: any
  build_runner: ^1.7.3
  build_test: ^0.10.12
  build_web_compilers: ^2.9.0
  pedantic: ^1.9.0
  test: any
  
# name: example
# description: A web app that uses AngularDart Components
# version: 1.0.1
# # homepage: https://www.example.com
# # author: insinfo <insinfo2008@gmail.com>

# environment:
#   sdk: '>=2.4.0 <3.0.0'

# dependencies:
#   angular: ^5.3.1
#   angular_components: ^0.13.0+1
#   angular_router: ^2.0.0-alpha+19
#   http: ^0.12.0+2
#   stream_transform: ^0.0.19
#   sass_builder: ^2.1.3
#   #firebase: ^5.0.4
#   #firebase_dart_ui: ^0.1.1
#   js: ^0.6.1+1
#   money: ^0.2.1
#   decimal: ^0.3.4
#   #ng_bootstrap: any
#   #ng_fontawesome: ^5.7.2+2
#   #modern_charts: ^0.1.17
#   #chartjs: ^0.5.1
#   #spreadsheet_decoder: ^1.0.1
#   c3: ^0.1.0
#   dio: ^3.0.3

#   essential_components: 0.1.45
#     #path: ../essential_components

# dev_dependencies:
#   angular_test: ^2.3.0
#   build_runner: ^1.7.2
#   build_test: ^0.10.9+1
#   build_web_compilers: ^2.7.1
#   pedantic: ^1.8.0
#   test: ^1.6.0
